import Head from "next/head";
import styles from "./app.module.scss";
import { Header } from "../components/header";
import { CoursesList } from "../components/courses-list/courses-list";
import { useWeb3React } from "@web3-react/core";
import { useEffect, useState } from "react";
import {
  CONTRACT_ABI,
  CONTRACT_ADDRESS,
  courses as localCourses,
} from "../constants";

export default function Home() {
  const { active, account, library, connector, activate, deactivate } =
    useWeb3React();

  const [courses, setCourses] = useState([]);

  async function getCoursesFromContract() {
    // const LearnContract = new library.eth.Contract(
    //   CONTRACT_ABI,
    //   CONTRACT_ADDRESS
    // );
    //
    // const coursesLen = await LearnContract.methods.getCoursesLength().call();
    // const res = [];
    //
    // for (let i = 0; i < coursesLen; i++) {
    //   let course = await LearnContract.methods.getSpecificCourseById(i).call();
    //
    //   res.push({
    //     id: course[0],
    //     title: course[1],
    //     description: course[2],
    //     difficulty: course[3],
    //     img: course[4],
    //   });
    // }
    return localCourses;
  }

  useEffect(() => {
    if (library) {
      getCoursesFromContract().then((res) => {
        setCourses(res);
      });
    }
  }, [library]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Learn2Earn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.wrapper}>
        <Header />
        {active ? (
          <CoursesList courses={courses} />
        ) : (
          <div>You should be connected</div>
        )}
      </main>
    </div>
  );
}
